Enabling multiple GPUs selection for GradCAM
jacobgil/pytorch-grad-cam pull request #98
Opened 2021-06-07 10:28 UTC by francescoalongi

Hello and thank you for your work. 
I slightly changed the code of the `Base_cam.py` file in order to accommodate the case in which the workstation has multiple GPUs.

I hope that this will make the code even more usable.

Thank you again,
Francesco

2021-09-12 19:22 UTC, jacobgil requested changes

2021-09-12 19:22 UTC, jacobgil commented on pytorch_grad_cam/base_cam.py
> +            input_tensor = input_tensor.to(self.cuda)
Since self.cuda is a boolean here, will this work? Doesn't it expect a cuda device like `torch.device('cuda:0')` ?

2021-09-13 16:54 UTC, francescoalongi commented on pytorch_grad_cam/base_cam.py
> +            input_tensor = input_tensor.to(self.cuda)
with this modification, self.cuda should be either False (when cuda is not needed and user wants to use the cpu), or a string indicating the gpu to be used ("cuda:0" or "cuda:1"...).

2021-09-14 06:56 UTC, jacobgil commented on pytorch_grad_cam/base_cam.py
> +            input_tensor = input_tensor.to(self.cuda)
Hi, thanks.
I just tried this:
>>> import torch
>>> a = torch.Tensor([1, 2, 3])
>>> a.to('cuda:0')
tensor([1., 2., 3.], device='cuda:0')
>>> import torch
>>> a = torch.Tensor([1, 2, 3])
>>> a.to(False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: to() received an invalid combination of arguments - got (bool), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (Tensor tensor, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 
 So .to(False) doesn't work at least in my torch version.

What am I missing?

2021-09-14 13:14 UTC, francescoalongi commented on pytorch_grad_cam/base_cam.py
> +            input_tensor = input_tensor.to(self.cuda)
That's correct, the only detail you are missing is that before sending the tensor to a specific device, a control is performed using the `if self.cuda` instruction at line 56.
If `self.cuda` is `False`, the instruction `input_tensor = input_tensor.to(self.cuda)` at line 57 will never be executed.

The instruction `input_tensor = input_tensor.to(self.cuda)` is executed only if `self.cuda` is something different than False, for instance a string like "cuda:0"

2021-09-14 13:19 UTC, jacobgil commented on pytorch_grad_cam/base_cam.py
> +            input_tensor = input_tensor.to(self.cuda)
Got it, makes sense, thanks!

2022-04-01 16:46 UTC, kingychiu commented on pytorch_grad_cam/base_cam.py
> +            input_tensor = input_tensor.to(self.cuda)
Thanks for having this PR. I find this useful as well. Why is this PR not merging?

Btw, in case the reason is about the breaking change. I think to not make a breaking change, might be we can keep the `use_cuda` and add a `cuda_device` parameter. If use_cuda is True then we call tensor.to(self.cuda_device)

2023-02-17 20:28 UTC, TRex22 commented
Id love to see this being done. For now Ill do a similar implementation in a fork to unblock myself

2023-02-24 14:35 UTC, francescoalongi commented
Hello @jacobgil, I know this is an old PR, but I would like to know whether this is a feature you think would be useful. If so, I can work on it to update it so that it will be ready to merge.

I personally think this might be useful, but before spending time working again on it I would like to understand whether you have plans to include this feature. Thank you!

2023-04-05 07:26 UTC, closed without merging